---
name: 'CI - Linting & Testing'

on:
  push:
  pull_request:
  schedule:
    - cron: '15 9 * * *'

jobs:
  linting:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Linting
        uses: ansible/ansible-lint-action@v6
        with:
          targets: "roles/"
          override-deps: |
            rich>=9.5.1,<11.0.0
          args: ""
